---
apiVersion: v1
kind: Secret
metadata:
  name: auth-service-db-secret
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: jdbc:postgresql://auth-db:5432/user_credentials_db
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATASOURCE_PASSWORD: postgres

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: ClusterIP
  selector:
    app: auth-service
  ports:
    - port: 8081
      targetPort: 8081

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: nikitayatsko/auth-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: JAVA_OPTS
              value: "-XX:+UseContainerSupport -Xmx256m -Xms512m"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://auth_db:5432/user_credentials_db"
          envFrom:
            - secretRef:
                name: auth-service-db-secret
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 5
            timeoutSeconds: 2

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            initialDelaySeconds: 80
            periodSeconds: 10
            timeoutSeconds: 2

          resources:
            requests:
              memory: "256Mi"
              cpu: "150m"
            limits:
              memory: "512Mi"
              cpu: "300m"
