--liquibase formatted sql

--changeset nyatska:1
CREATE TABLE auth_users(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT UNIQUE NOT NULL,
    username VARCHAR(30) UNIQUE NOT NULL,
    password VARCHAR(80) NOT NULL,
    role VARCHAR(15) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE refresh_tokens(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT UNIQUE REFERENCES auth_users(user_id),
    token TEXT NOT NULL UNIQUE,
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


--changeset nyatska:2
INSERT INTO auth_users (user_id, username, password, role)
VALUES (4 ,'admin', '$2a$10$ixyUizBVZiooVBSnwMmC4e4sa0/dI0X6S.jFs2k1hL3sAkJAsgS0K', 'ADMIN');
